# Generated by Django 4.2.7 on 2023-12-02 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='audio_files/')),
                ('transcription', models.TextField()),
                ('suitability_result', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='AudioFile',
        ),
    ]
